[project]
name = "ai-iris-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.8",
    "httpx>=0.28.1",
    "joblib>=1.5.3",
    "pytest>=9.0.2",
    "scikit-learn>=1.8.0",
    "uvicorn>=0.40.0",
]
